# ZeroClaw NixOS Module
# Comprehensive service module for the ZeroClaw AI personal assistant.
#
# Usage in your NixOS configuration:
#   imports = [ ./nixos/zeroclaw-module.nix ];
#   services.zeroclaw = {
#     enable = true;
#     provider = "openrouter";
#     apiKeyFile = "/run/secrets/zeroclaw-api-key";
#   };

{ config, lib, pkgs, ... }:

let
  cfg = config.services.zeroclaw;

  # ── Build the zeroclaw package from source ───────────────────────
  zeroclawPackage = pkgs.rustPlatform.buildRustPackage rec {
    pname = "zeroclaw";
    version = "0.5.2";

    src = pkgs.fetchFromGitHub {
      owner = "zeroclaw-labs";
      repo = "zeroclaw";
      rev = "master"; # Pin to a specific tag/commit in production
      # Run `nix-prefetch-url --unpack <tarball-url>` and replace the value below.
      hash = lib.fakeSha256;
    };

    cargoLock = {
      lockFile = "${src}/Cargo.lock";
      allowBuiltinFetchGit = true;
    };

    # Build-time native dependencies
    nativeBuildInputs = with pkgs; [
      pkg-config
      cmake
      protobuf
      nodejs_22 # For building web dashboard assets
    ];

    # Runtime/link-time dependencies
    buildInputs = with pkgs; [
      openssl
      sqlite
      libudev-zero # For USB device enumeration (nusb)
    ] ++ lib.optionals stdenv.isLinux [
      libusb1
    ];

    # Enable all the Cargo features the user selected
    buildFeatures = cfg.cargoFeatures;

    # Build the web dashboard before the Rust build embeds it
    preBuild = ''
      if [ -d web ] && [ -f web/package.json ]; then
        pushd web
        npm ci --ignore-scripts
        npm run build
        popd
      fi
    '';

    # Install shell completions alongside the binary
    postInstall = ''
      installShellCompletion --cmd zeroclaw \
        --bash <($out/bin/zeroclaw completions bash 2>/dev/null || true) \
        --zsh  <($out/bin/zeroclaw completions zsh  2>/dev/null || true) \
        --fish <($out/bin/zeroclaw completions fish 2>/dev/null || true)
    '';

    meta = with lib; {
      description = "Fast, small, fully autonomous AI personal assistant infrastructure";
      homepage = "https://github.com/zeroclaw-labs/zeroclaw";
      license = with licenses; [ mit asl20 ];
      platforms = platforms.linux;
      mainProgram = "zeroclaw";
    };
  };

  # ── Generate the TOML config file from NixOS options ────────────
  configFile = pkgs.writeText "zeroclaw-config.toml" ''
    # Auto-generated by NixOS module — do not edit manually.
    [provider]
    name = "${cfg.provider}"
    ${lib.optionalString (cfg.model != null) ''model = "${cfg.model}"''}
    ${lib.optionalString (cfg.temperature != null) ''temperature = ${toString cfg.temperature}''}

    [gateway]
    host = "${cfg.gateway.host}"
    port = ${toString cfg.gateway.port}

    ${lib.optionalString cfg.reasoning.enable ''
    [reasoning]
    enabled = true
    ''}

    ${lib.optionalString (cfg.workspace != null) ''
    [workspace]
    path = "${cfg.workspace}"
    ''}

    ${lib.optionalString cfg.proxy.enable ''
    [proxy]
    enabled = true
    ${lib.optionalString (cfg.proxy.http != null)  ''http_proxy  = "${cfg.proxy.http}"''}
    ${lib.optionalString (cfg.proxy.https != null) ''https_proxy = "${cfg.proxy.https}"''}
    ${lib.optionalString (cfg.proxy.all != null)   ''all_proxy   = "${cfg.proxy.all}"''}
    ${lib.optionalString (cfg.proxy.noProxy != null) ''no_proxy = "${cfg.proxy.noProxy}"''}
    scope = "${cfg.proxy.scope}"
    ''}

    ${lib.optionalString cfg.webSearch.enable ''
    [web_search]
    enabled = true
    provider = "${cfg.webSearch.provider}"
    max_results = ${toString cfg.webSearch.maxResults}
    timeout_secs = ${toString cfg.webSearch.timeoutSecs}
    ''}

    ${lib.optionalString cfg.storage.enable ''
    [storage]
    provider = "${cfg.storage.provider}"
    ${lib.optionalString (cfg.storage.dbUrl != null) ''db_url = "${cfg.storage.dbUrl}"''}
    connect_timeout_secs = ${toString cfg.storage.connectTimeoutSecs}
    ''}

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: channelCfg: ''
    [channels.${name}]
    enabled = ${lib.boolToString channelCfg.enable}
    ${channelCfg.extraConfig}
    '') cfg.channels)}

    ${cfg.extraConfig}
  '';

in
{
  # ══════════════════════════════════════════════════════════════════
  #  Module Options
  # ══════════════════════════════════════════════════════════════════

  options.services.zeroclaw = {

    enable = lib.mkEnableOption "ZeroClaw AI personal assistant service";

    package = lib.mkOption {
      type = lib.types.package;
      default = zeroclawPackage;
      defaultText = lib.literalExpression "zeroclawPackage";
      description = "The ZeroClaw package to use. Override to supply a prebuilt binary.";
    };

    # ── Cargo build features ──────────────────────────────────────
    cargoFeatures = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "observability-prometheus"
        "channel-nostr"
        "skill-creation"
      ];
      description = ''
        Cargo feature flags to compile into the ZeroClaw binary.

        Available features:
          - observability-prometheus  Prometheus /metrics endpoint
          - observability-otel        OpenTelemetry OTLP exporter
          - channel-nostr             Nostr relay channel
          - channel-matrix            Matrix E2EE channel
          - channel-lark              Lark / Feishu channel
          - channel-feishu            Alias for channel-lark
          - browser-native            Fantoccini browser automation
          - hardware                  USB + serial peripheral support
          - peripheral-rpi            Raspberry Pi GPIO (rppal)
          - memory-postgres           PostgreSQL memory backend
          - sandbox-landlock          Landlock LSM sandboxing
          - sandbox-bubblewrap        Bubblewrap sandboxing
          - rag-pdf                   PDF ingestion for RAG
          - plugins-wasm              Extism WASM plugin runtime
          - whatsapp-web              Native WhatsApp Web client
          - skill-creation            Autonomous skill creation
          - probe                     STM32/probe-rs hardware debugging
      '';
    };

    # ── Core provider / model settings ────────────────────────────
    provider = lib.mkOption {
      type = lib.types.enum [
        "openrouter" "openai" "anthropic" "gemini" "google"
        "ollama" "venice" "groq" "mistral" "deepseek" "xai"
        "together" "fireworks" "perplexity" "cohere" "moonshot"
        "glm" "minimax" "qianfan" "dashscope" "zai" "synthetic"
        "opencode" "vercel" "cloudflare"
      ];
      default = "openrouter";
      description = "LLM provider backend to use.";
    };

    model = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "anthropic/claude-sonnet-4-6";
      description = "Model identifier to use with the selected provider.";
    };

    temperature = lib.mkOption {
      type = lib.types.nullOr lib.types.float;
      default = null;
      example = 0.7;
      description = "Sampling temperature for LLM inference.";
    };

    apiKeyFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = "/run/secrets/zeroclaw-api-key";
      description = ''
        Path to a file containing the API key (newline-trimmed).
        Loaded at service start; the file is never written to the Nix store.

        For provider-specific keys, use `environmentFiles` instead.
      '';
    };

    environmentFiles = lib.mkOption {
      type = lib.types.listOf lib.types.path;
      default = [];
      example = [ "/run/secrets/zeroclaw.env" ];
      description = ''
        List of EnvironmentFile paths loaded by systemd.
        Use this for multi-provider key setups, e.g.:

          OPENROUTER_API_KEY=sk-or-v1-...
          ANTHROPIC_API_KEY=sk-ant-...
          OPENAI_API_KEY=sk-...
          BRAVE_API_KEY=...
      '';
    };

    # ── Workspace ─────────────────────────────────────────────────
    workspace = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "/var/lib/zeroclaw/workspace";
      description = "Workspace directory for agent file operations.";
    };

    # ── Reasoning ─────────────────────────────────────────────────
    reasoning = {
      enable = lib.mkEnableOption "extended thinking / reasoning mode for supported models";
    };

    # ── Gateway (HTTP API + Web Dashboard) ────────────────────────
    gateway = {
      host = lib.mkOption {
        type = lib.types.str;
        default = "127.0.0.1";
        description = "Bind address for the HTTP gateway.";
      };

      port = lib.mkOption {
        type = lib.types.port;
        default = 42617;
        description = "TCP port for the HTTP gateway.";
      };

      openFirewall = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Whether to open the gateway port in the NixOS firewall.";
      };
    };

    # ── Storage backend ───────────────────────────────────────────
    storage = {
      enable = lib.mkEnableOption "explicit storage backend configuration (default: sqlite)";

      provider = lib.mkOption {
        type = lib.types.enum [ "sqlite" "postgres" ];
        default = "sqlite";
        description = "Persistent storage backend.";
      };

      dbUrl = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "postgres://localhost/zeroclaw";
        description = "Database connection URL for postgres backend.";
      };

      connectTimeoutSecs = lib.mkOption {
        type = lib.types.int;
        default = 5;
        description = "Database connection timeout in seconds.";
      };
    };

    # ── Proxy ─────────────────────────────────────────────────────
    proxy = {
      enable = lib.mkEnableOption "HTTP/SOCKS proxy for provider traffic";

      http = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "http://proxy.example.com:8080";
        description = "HTTP proxy URL.";
      };

      https = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "HTTPS proxy URL.";
      };

      all = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "socks5://proxy.example.com:1080";
        description = "SOCKS/catch-all proxy URL.";
      };

      noProxy = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = "localhost,127.0.0.1";
        description = "Comma-separated list of hosts to bypass the proxy.";
      };

      scope = lib.mkOption {
        type = lib.types.enum [ "environment" "zeroclaw" "services" ];
        default = "zeroclaw";
        description = "Proxy scope: environment (global), zeroclaw (agent only), or services (named providers).";
      };
    };

    # ── Web search ────────────────────────────────────────────────
    webSearch = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable web search tool.";
      };

      provider = lib.mkOption {
        type = lib.types.enum [ "duckduckgo" "brave" ];
        default = "duckduckgo";
        description = "Web search backend.";
      };

      maxResults = lib.mkOption {
        type = lib.types.int;
        default = 5;
        description = "Maximum search results to return.";
      };

      timeoutSecs = lib.mkOption {
        type = lib.types.int;
        default = 15;
        description = "Search request timeout in seconds.";
      };
    };

    # ── Chat channel integrations ─────────────────────────────────
    channels = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          enable = lib.mkEnableOption "this chat channel integration";

          extraConfig = lib.mkOption {
            type = lib.types.lines;
            default = "";
            description = "Additional TOML configuration for this channel.";
          };
        };
      });
      default = {};
      example = lib.literalExpression ''
        {
          discord = {
            enable = true;
            extraConfig = '''
              token_file = "/run/secrets/discord-token"
            ''';
          };
          matrix = {
            enable = true;
            extraConfig = '''
              homeserver = "https://matrix.org"
              user = "@zeroclaw:matrix.org"
            ''';
          };
        }
      '';
      description = ''
        Chat channel integrations.
        Supported channels: discord, telegram, slack, matrix, lark, feishu,
        dingtalk, nostr, whatsapp, irc, email.
      '';
    };

    # ── Browser automation (for browser-native feature) ───────────
    browserAutomation = {
      enable = lib.mkEnableOption "browser automation via geckodriver/chromedriver";

      backend = lib.mkOption {
        type = lib.types.enum [ "geckodriver" "chromedriver" ];
        default = "geckodriver";
        description = "WebDriver backend for browser automation.";
      };
    };

    # ── Desktop environment integration ───────────────────────────
    desktopIntegration = {
      enable = lib.mkEnableOption "desktop environment integration (tray, notifications, autostart)";

      autostart = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Start ZeroClaw gateway automatically on graphical login.";
      };

      port = lib.mkOption {
        type = lib.types.port;
        default = 42618;
        description = "TCP port for the desktop companion gateway (user-level service).";
      };
    };

    # ── Raw extra config ──────────────────────────────────────────
    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Additional raw TOML appended to the config file.";
    };

    # ── systemd service tuning ────────────────────────────────────
    user = lib.mkOption {
      type = lib.types.str;
      default = "zeroclaw";
      description = "System user under which the service runs.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "zeroclaw";
      description = "System group under which the service runs.";
    };

    dataDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/zeroclaw";
      description = "State directory for ZeroClaw data, config, and SQLite databases.";
    };
  };

  # ══════════════════════════════════════════════════════════════════
  #  Module Implementation
  # ══════════════════════════════════════════════════════════════════

  config = lib.mkIf cfg.enable {

    # ── System packages ───────────────────────────────────────────
    environment.systemPackages = [
      cfg.package
    ]
    ++ lib.optionals cfg.browserAutomation.enable (
      if cfg.browserAutomation.backend == "geckodriver" then [
        pkgs.firefox
        pkgs.geckodriver
      ] else [
        pkgs.chromium
        pkgs.chromedriver
      ]
    )
    ++ lib.optionals cfg.desktopIntegration.enable [
      pkgs.libnotify
    ];

    # ── Firewall ──────────────────────────────────────────────────
    networking.firewall.allowedTCPPorts =
      lib.mkIf cfg.gateway.openFirewall [ cfg.gateway.port ];

    # ── System user & group ───────────────────────────────────────
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      home = cfg.dataDir;
      createHome = true;
      description = "ZeroClaw AI assistant service";
    };

    users.groups.${cfg.group} = {};

    # ── Main systemd service ──────────────────────────────────────
    systemd.services.zeroclaw = {
      description = "ZeroClaw AI Personal Assistant Gateway";
      after = [ "network-online.target" ]
        ++ lib.optionals (cfg.storage.provider == "postgres") [ "postgresql.service" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      environment = {
        HOME = cfg.dataDir;
        ZEROCLAW_GATEWAY_HOST = cfg.gateway.host;
        ZEROCLAW_GATEWAY_PORT = toString cfg.gateway.port;
        PROVIDER = cfg.provider;
      }
      // lib.optionalAttrs (cfg.model != null) {
        ZEROCLAW_MODEL = cfg.model;
      }
      // lib.optionalAttrs (cfg.temperature != null) {
        ZEROCLAW_TEMPERATURE = toString cfg.temperature;
      }
      // lib.optionalAttrs (cfg.workspace != null) {
        ZEROCLAW_WORKSPACE = cfg.workspace;
      }
      // lib.optionalAttrs cfg.reasoning.enable {
        ZEROCLAW_REASONING_ENABLED = "true";
      }
      // lib.optionalAttrs cfg.proxy.enable (
        lib.optionalAttrs (cfg.proxy.http != null)  { ZEROCLAW_HTTP_PROXY = cfg.proxy.http; }
        // lib.optionalAttrs (cfg.proxy.https != null) { ZEROCLAW_HTTPS_PROXY = cfg.proxy.https; }
        // lib.optionalAttrs (cfg.proxy.all != null)   { ZEROCLAW_ALL_PROXY = cfg.proxy.all; }
        // lib.optionalAttrs (cfg.proxy.noProxy != null) { ZEROCLAW_NO_PROXY = cfg.proxy.noProxy; }
        // { ZEROCLAW_PROXY_ENABLED = "true"; ZEROCLAW_PROXY_SCOPE = cfg.proxy.scope; }
      );

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.group;

        ExecStart = "${cfg.package}/bin/zeroclaw gateway --port ${toString cfg.gateway.port} --host ${cfg.gateway.host}";

        # Secret management
        EnvironmentFile = cfg.environmentFiles
          ++ lib.optional (cfg.apiKeyFile != null) "/run/zeroclaw/env";

        # Config file setup and optional API key loading
        ExecStartPre = [
          "+${pkgs.coreutils}/bin/mkdir -p ${cfg.dataDir}/.zeroclaw"
          "+${pkgs.coreutils}/bin/cp ${configFile} ${cfg.dataDir}/.zeroclaw/config.toml"
          "+${pkgs.coreutils}/bin/chown -R ${cfg.user}:${cfg.group} ${cfg.dataDir}"
        ] ++ lib.optionals (cfg.apiKeyFile != null) [
          "+${pkgs.coreutils}/bin/mkdir -p /run/zeroclaw"
          "+${pkgs.writeShellScript "zeroclaw-load-key" ''
            KEY=$(cat "${cfg.apiKeyFile}" | tr -d '\n')
            echo "API_KEY=$KEY" > /run/zeroclaw/env
            chmod 600 /run/zeroclaw/env
            chown ${cfg.user}:${cfg.group} /run/zeroclaw/env
          ''}"
        ];

        # Directories
        StateDirectory = "zeroclaw";
        RuntimeDirectory = "zeroclaw";
        WorkingDirectory = cfg.dataDir;

        # Hardening
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = !lib.elem "hardware" cfg.cargoFeatures;
        NoNewPrivileges = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
        RestrictNamespaces = true;
        LockPersonality = true;
        MemoryDenyWriteExecute = !lib.elem "plugins-wasm" cfg.cargoFeatures;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallFilter = [ "@system-service" "~@privileged" ];
        ReadWritePaths = [
          cfg.dataDir
        ] ++ lib.optional (cfg.workspace != null) cfg.workspace;

        # Restart behaviour
        Restart = "on-failure";
        RestartSec = 5;
        WatchdogSec = 120;

        # Resource limits matching the Docker Compose config
        CPUQuota = "200%";
        MemoryMax = "512M";
        MemoryHigh = "384M";
        TasksMax = 256;
      };
    };

    # ── Workspace directory ───────────────────────────────────────
    systemd.tmpfiles.rules = lib.optionals (cfg.workspace != null) [
      "d ${cfg.workspace} 0750 ${cfg.user} ${cfg.group} -"
    ];

    # ── Desktop autostart (user-level service) ────────────────────
    systemd.user.services.zeroclaw-desktop = lib.mkIf cfg.desktopIntegration.enable {
      description = "ZeroClaw Desktop Companion";
      wantedBy = lib.mkIf cfg.desktopIntegration.autostart [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/zeroclaw gateway --port ${toString cfg.desktopIntegration.port} --host 127.0.0.1";
        Restart = "on-failure";
        RestartSec = 3;
      };
    };

    # ── XDG desktop entry ─────────────────────────────────────────
    environment.etc."xdg/autostart/zeroclaw.desktop" = lib.mkIf cfg.desktopIntegration.enable {
      text = ''
        [Desktop Entry]
        Type=Application
        Name=ZeroClaw AI Assistant
        Comment=Autonomous AI personal assistant
        Exec=${cfg.package}/bin/zeroclaw gateway
        Terminal=false
        StartupNotify=false
        Categories=Utility;
        X-GNOME-Autostart-enabled=${lib.boolToString cfg.desktopIntegration.autostart}
      '';
    };

    # ── Browser automation WebDriver service ──────────────────────
    systemd.services.zeroclaw-webdriver = lib.mkIf cfg.browserAutomation.enable {
      description = "WebDriver backend for ZeroClaw browser automation";
      after = [ "zeroclaw.service" ];
      wantedBy = [ "zeroclaw.service" ];
      partOf = [ "zeroclaw.service" ];

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.group;
        ExecStart =
          if cfg.browserAutomation.backend == "geckodriver"
          then "${pkgs.geckodriver}/bin/geckodriver --port 4444 --host 127.0.0.1"
          else "${pkgs.chromedriver}/bin/chromedriver --port=4444 --whitelisted-ips=127.0.0.1";
        Restart = "on-failure";
        RestartSec = 3;

        # Hardening
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        NoNewPrivileges = true;
      };
    };

    # ── Prometheus monitoring endpoint assertion ──────────────────
    warnings = lib.optionals
      (!(lib.elem "observability-prometheus" cfg.cargoFeatures)
       && config.services.prometheus.enable or false)
      [
        "ZeroClaw: Prometheus is enabled in NixOS but 'observability-prometheus' is not in cargoFeatures. Metrics will not be exported."
      ];

    # ── Assertions ────────────────────────────────────────────────
    assertions = [
      {
        assertion = cfg.apiKeyFile != null || cfg.environmentFiles != [] || cfg.provider == "ollama";
        message = "services.zeroclaw: You must set apiKeyFile or environmentFiles (unless using 'ollama' provider which needs no key).";
      }
      {
        assertion = cfg.storage.provider != "postgres" || lib.elem "memory-postgres" cfg.cargoFeatures;
        message = "services.zeroclaw: Storage provider 'postgres' requires 'memory-postgres' in cargoFeatures.";
      }
      {
        assertion = !cfg.browserAutomation.enable || lib.elem "browser-native" cfg.cargoFeatures;
        message = "services.zeroclaw: browserAutomation requires 'browser-native' in cargoFeatures.";
      }
    ];
  };
}
